### PR TITLE
Vienna 2023 update

### PR DESCRIPTION
**Pull request by torotil**
- Fixed the entries for FolkTanz-Abende
- Added MuwiFolxTanz
- Added Hotel Palindrone

### CODE REVIEW

**Review by qwandor — APPROVED** [review]
I've removed the aliases and merges for now so we can get this in.

**Comment by qwandor** [comment]
Oh, one minor question though: are "TanzFolk Vienna" and "FolkTanz Wien" actually the same thing? There are currently are a bunch of old events listed under [TanzFolk Vienna](https://folkdance.page/?date=all&organisation=TanzFolk+Vienna) which we can change to FolkTanz Wien if that is the correct name.

**Comment by torotil** [comment]
That question is more complicated than you think. :sweat_smile:

- TanzFolk Vienna is just the name of the facebook group.
- FolkTanz-Wien is the name used by those who organize the „FolkTanz-Abend“ events, and also the website https://folktanz.at + the newsletter.
- MuwiFolxTanz is a series of events organized by team whose organization doesn’t have a name. They also use MuwiFolxTanz as the FB page to post the event.

**Comment by qwandor** [comment]
I see. So is FolkTanz-Wien also the organiser of the "VotivFolk" and "Hof 3-Folk" events? Or is that something else?

**Comment by torotil** [comment]
> I see. So is FolkTanz-Wien also the organiser of the "VotivFolk" and "Hof 3-Folk" events? Or is that something else?

No, they are usually organized by Michaela Perkic.

**Comment by qwandor** [comment]
Thanks! I've fixed those up.

**Pull request merged**
