### PR TITLE
Create st_albans_friday_folk.yaml

### PR DESCRIPTION
**Pull request by tenbob**
Add event data for Friday Folk, St Albans

### CODE REVIEW

**Comment by qwandor** [comment]
Thanks for the PR! I believe we already have this event in [events/uk/webfeet.yaml](https://github.com/qwandor/dancelist-data/blob/main/events/uk/webfeet.yaml#L835) (imported from Webfeet), so could you add the extra details there instead?

**Comment by tenbob** [comment]
Hi @qwandor. Sorry. I'm unfamiliar with how this all works. You are correct. The same event already appears in [events/uk/webfeet.yaml](https://github.com/qwandor/dancelist-data/blob/main/events/uk/webfeet.yaml#L835). But I'm not sure who is the 'owner/maintainer' of that file. It seems to contain lots of different events from multiple organisers. 

I thought it was better to start our own file for events that we are organising ourselves. Typically there will be 3 or 4 per year. What do you recommend?

**Comment by qwandor** [comment]
No worries!

`webfeet.yaml` has UK events which are (semi-)automatically imported from https://www.webfeet.org/events.html, so yeah, it has events from lots of different organisers.

It's fine to edit events in that file, your edits should get kept when I next run the import. It's also fine to have a separate file if you prefer, and that probably makes life easier for you if you expect to add events regularly, but in that case please delete the copy of the event from `webfeet.yaml` and put your new file under the uk directory.

**Comment by tenbob** [comment]
I have redone this as suggested. I moved st_albans_friday_folk.yaml to the correct uk directory. Also removed the duplicate reference to our event in webfeet.yaml. Hope this works.

**Review by qwandor — APPROVED** [review]

**Comment by qwandor** [comment]
Thanks! This should be live now.

**Comment by tenbob** [comment]
Looks good. Thanks for your help.

**Pull request merged**
