### PR TITLE
Create scandimoot.yml

### PR DESCRIPTION
**Pull request by dabley**
Added details for Scandimoot

### CODE REVIEW

**Comment by qwandor** [comment]
Thanks for the PR! Merged and released. (I had to rename the file, the current code only looks for files ending in `.yaml` not `.yml`.)

**Comment by dabley** [comment]
Sorry, my mistake with the filename.

**Comment by qwandor** [comment]
Ah, currently it only pulls out Facebook event links, i.e. those starting with the prefix `https://www.facebook.com/events/`. It would probably be good to have a way to display other links too though.

**Comment by dabley** [comment]
Why not just pull out any facebook link? For annual events, it is more common that organisers create these as facebook pages rather than just events.

**Pull request merged**
